name: teams_dart
description: A project for randomly and evenly picking teams.
version: 0.1.0
repository: https://github.com/ernestoittig/teams_dart
author: Ernesto Ittig <e.ittig@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  effective_dart: ^1.1.1
  test: ^1.9.4

publish_to: none

executables:
  teams_dart:
